name: Build and Publish Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_publish:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish project
        run: dotnet publish GameLibrary/GameLibrary.csproj --configuration Release --output ./publish
      
      - name: Upload published artifacts
        uses: actions/upload-artifact@v5
        with:
          name: app-artifacts
          path: ./publish
